# Generated by Django 5.0.3 on 2024-03-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='group',
            field=models.CharField(default='other', max_length=50),
        ),
    ]
